close all hidden
if ~exist( 'df' , 'var' )
scan_data = all_scans                                                       ;
scan_data( isnan( scan_data ) )     = 0                                     ;    
df      = designfilt(   'lowpassfir' ,                                      ...
                        'DesignMethod' ,           'equiripple' ,           ...
                        'PassbandFrequency' ,       0.15 ,                  ...
                        'StopbandFrequency' ,       0.2 ,                   ...
                        'PassbandRipple' ,          1 ,                     ...
                        'StopbandAttenuation' ,     60 ,                    ...
                        'SampleRate' ,              20 )                    ;
end
y       = filtfilt( df , scan_data )                                        ;     
subplot( 1 , 2 , 1 )
imagesc( y )
subplot( 1 , 2 , 2 )
imagesc( all_scans )